---
title: "MHW_EBUS"
author: "Amieroh Abrahams"
date: "03 June 2019"
output: html_document
---

# Loading packages
# MHW occuring in EBUS

```{r}
library(doMC); doMC::registerDoMC(cores = 4) # multi-core
require(mgcv)
library(data.table)
library(readr)
library(dplyr)
library(plyr)
library(lubridate)
library(tidyverse)
library(heatwaveR)
```

# Using the detect event function to detect when upwelling events occured. 

```{r}

BC_clim <- read_csv("/home/amieroh/Documents/Masters_2019/Upwelling/global_EBUS/Climatologies/MHW/BC_MHW_climatology.csv")
CalC_clim <- read_csv("/home/amieroh/Documents/Masters_2019/Upwelling/global_EBUS/Climatologies/MHW/CalC_MHW_climatology.csv")
CC_clim <- read_csv("/home/amieroh/Documents/Masters_2019/Upwelling/global_EBUS/Climatologies/MHW/CC_MHW_climatology.csv")
HC_clim <- read_csv("/home/amieroh/Documents/Masters_2019/Upwelling/global_EBUS/Climatologies/MHW/HC_MHW_climatology.csv")

eventDir <- "/home/amieroh/Documents/Masters_2019/Upwelling/global_EBUS/MHW/events"
               
OISST_detect2 <- function(dat) {
  require(heatwaveR)
  out <- heatwaveR::detect_event(dat)
  event <- out$event
  return(event)
}

setClass('myDate')
setAs(from = "character", to = "myDate", def = function(from) as.Date(fastPOSIXct(from, tz = NULL)))

BC.ev <- ddply(BC_clim, .(lon, lat), OISST_detect2, .parallel = TRUE, .progress = "text")
fwrite(BC.ev,
       file = paste0(eventDir, "/BC.ev_MHW.csv"),
       append = FALSE)
CalC.ev <- ddply(CalC_clim, .(lon, lat), OISST_detect2, .parallel = TRUE, .progress = "text")
fwrite(CalC.ev,
       file = paste0(eventDir, "/CalC.ev _MHW.csv"),
       append = FALSE)
HC.ev <- ddply(HC_clim, .(lon, lat), OISST_detect2, .parallel = TRUE, .progress = "text")
fwrite(HC.ev,
       file = paste0(eventDir, "/HC.ev _MHW.csv"),
       append = FALSE)
CC.ev <- ddply(CC_clim, .(lon, lat), OISST_detect2, .parallel = TRUE, .progress = "text")
fwrite(CC.ev,
       file = paste0(eventDir, "/CC.ev _MHW.csv"),
       append = FALSE)
```

# Here I determine the number of events per annum

```{r}

events_PADir <- "/home/amieroh/Documents/Masters_2019/Upwelling/global_EBUS/MHW/events_PA"

BC.ev <- read_csv("/home/amieroh/Documents/Masters_2019/Upwelling/global_EBUS/MHW/events/BC.ev_MHW.csv")
CalC.ev <- read_csv("/home/amieroh/Documents/Masters_2019/Upwelling/global_EBUS/MHW/events/CalC.ev _MHW.csv")
CC.ev <- read_csv("/home/amieroh/Documents/Masters_2019/Upwelling/global_EBUS/MHW/events/CC.ev _MHW.csv")
HC.ev <- read_csv("/home/amieroh/Documents/Masters_2019/Upwelling/global_EBUS/MHW/events/HC.ev _MHW.csv")

mean_intensity <- function(events) {
  freq <- events %>%
    dplyr::mutate(year = year(date_start)) %>%
    dplyr::select(-date_start, -date_end, -date_peak) %>%
    dplyr::group_by(lon, lat, year) %>%
    dplyr::summarise(y = mean(intensity_mean)) %>%
    dplyr::ungroup() %>%
    as.tibble()
}

# Annual mean intensity
BC_annual <- mean_intensity(BC.ev)
fwrite(BC_annual,
       file = paste0(events_PADir, "/BC_annual.csv"),
       append = FALSE)
CalC_annual <- mean_intensity(CalC.ev)
fwrite(CalC_annual,
       file = paste0(events_PADir, "/CalC_annual.csv"),
       append = FALSE)
CC_annual <- mean_intensity(CC.ev)
fwrite(CC_annual,
       file = paste0(events_PADir, "/CC_annual.csv"),
       append = FALSE)
HC_annual <- mean_intensity(HC.ev)
fwrite(HC_annual,
       file = paste0(events_PADir, "/HC_annual.csv"),
       append = FALSE)
```

# linear function

```{r}
linFun <- function(annualEvent, poissan = FALSE) {
  if (poissan) {
    mod <- glm(y ~ year, family = poisson(link = "log"), data = annualEvent)
  }
  else {
    mod <- lm(y ~ year, data = annualEvent)
  }
  trend <- data.frame(slope = summary(mod)$coefficients[2,1] * 10, pval = summary(mod)$coefficients[2,4])
  trend$pbracket <- cut(trend$pval, breaks = c(0, 0.001, 0.01, 0.05, 1))
  return(trend)
}
BC_annual_int <- ddply(BC_annual, .(lon, lat), linFun, poissan = FALSE, .parallel = TRUE)
```

# Maximum intensity trend
# Calculte the number of events per annum

```{r}

maxInt <- "/home/amieroh/Documents/Masters_2019/Upwelling/global_EBUS/MHW/maxInt_annual"

max_intensity <- function(events) {
  freq <- events %>%
    dplyr::mutate(year = year(date_start)) %>%
    dplyr::select(-date_start, -date_end, -date_peak) %>%
    dplyr::group_by(lon, lat, year) %>%
    dplyr::summarise(y = mean(intensity_max)) %>%
    dplyr::ungroup() %>%
    as.tibble()
}

# Do the annual MaxInts
BC_annual_max <- max_intensity(BC.ev)
fwrite(BC_annual_max,
       file = paste0(maxInt, "/BC_annual_max.csv"),
       append = FALSE)
CalC_annual_max <- max_intensity(CalC.ev)
fwrite(CalC_annual_max,
       file = paste0(maxInt, "/CalC_annual_max.csv"),
       append = FALSE)
CC_annual_max <- max_intensity(CC.ev)
fwrite(CC_annual_max,
       file = paste0(maxInt, "/CC_annual_max.csv"),
       append = FALSE)
HC_annual_max <- max_intensity(HC.ev)
fwrite(HC_annual_max,
       file = paste0(maxInt, "/HC_annual_max.csv"),
       append = FALSE)
```

# The duration of an upwelling event

```{r}

durationDir <- "/home/amieroh/Documents/Masters_2019/Upwelling/global_EBUS/MHW/events_dur"

Duration <- function(events) {
  dur <- events %>%
    dplyr::group_by(lon, lat) %>%
    dplyr::summarise(y = mean(duration, na.rm = TRUE)) %>%
    as.tibble()
}
BC_Duration <- Duration(BC.ev)
fwrite(BC_Duration,
       file = paste0(durationDir, "/BC_Duration.csv"),
       append = FALSE)
CalC_Duration <- Duration(CalC.ev)
fwrite(CalC_Duration,
       file = paste0(durationDir, "/CalC_Duration.csv"),
       append = FALSE)
CC_Duration <- Duration(CC.ev)
fwrite(CC_Duration,
       file = paste0(durationDir, "/CC_Duration.csv"),
       append = FALSE)
HC_Duration <- Duration(HC.ev)
fwrite(HC_Duration,
       file = paste0(durationDir, "/HC_Duration.csv"),
       append = FALSE)
```




