---
title: "netCDF2CSV_CMC"
author: "Amieroh Abrahams"
date: "26 May 2019"
output: html_document
---

# Loading libraries

```{r}
library(ncdf4) # library for processing netCDFs
library(ncdf4)
library(data.table)
library(tidyverse)
library(reshape2)
library(plyr)
library(lubridate)
library(stringr)
library(doMC); doMC::registerDoMC(cores = 4)
library(heatwaveR)
```

```{r}
ncDir <- "/home/amieroh/Documents/Data/Datasets/CMC_EBUS/BC"
csvDir <- "/home/amieroh/Documents/spatial/data/csv/CMC"

bbox <- data.frame(BC = c(-35, -25, 15, 20), # Benguela Current
                   CC = c(25, 35, 340, 355), # Canary Current
                   CalC = c(35, 45, 225, 240), # California Current
                   HC = c(-17.5, -7.5, 275, 290), # Humboldt Current
                   row.names = c("latmin", "latmax", "lonmin", "lonmax"))


#          1         2         3         4         5         6        7
# 123456789012345678901234567890123456789012345678901234567890123456789012
# 19910901120000-CMC-L4_GHRSST-SSTfnd-CMC0.2deg-GLOB-v02.0-fv02.0_subset.nc

read_nc <- function(ncDir = ncDir, region = region, csvDir = csvDir) {
  coords <- bbox[, region]
  ncList <- list.files(path = paste0(ncDir, "/", region), pattern = "*.nc", full.names = TRUE, include.dirs = TRUE)
  ncFirst <- head(list.files(path = paste0(ncDir, "/", region), pattern = "*.nc", full.names = FALSE), 1)
  ncLast <- tail(list.files(path = paste0(ncDir, "/", region), pattern = "*.nc", full.names = FALSE), 1)
  strtDate <- str_sub(ncFirst, start = 1, end = 8)
  endDate <- str_sub(ncLast, start = 1, end = 8)
  ncFun <- function(ncFile = ncFile, region = region, csvDir = csvDir) {
    nc <- nc_open(ncFile)
    pathLen <- nchar(paste0(ncDir, "/", region)) + 1
    fNameStem <-
      substr(ncFile, pathLen + 9, pathLen + 80)
    fDate <- substr(ncFile, pathLen + 1, pathLen + 8)
    sst <- ncvar_get(nc, varid = "analysed_sst") %>%
      round(4)
    dimnames(sst) <- list(lon = nc$dim$lon$vals,
                          lat = nc$dim$lat$vals)
    nc_close(nc)
    sst <-
      as.data.frame(melt(sst, value.name = "temp"), row.names = NULL) %>%
      mutate(t = ymd(fDate)) %>%
      na.omit()
    fwrite(sst,
           file = paste0(csvDir, "/", region, "-", fNameStem, "-", strtDate, "-", endDate, ".csv"),
           append = TRUE, col.names = FALSE)
    rm(sst)
  }
  llply(ncList, ncFun, region = region, csvDir = csvDir, .parallel = TRUE)
}

# the list of files
ncList <- list.files(path = nc.dir, pattern = "*.nc", full.names = TRUE, include.dirs = TRUE)
strtDate <- str_sub(ncList[1], start = 1, end = 8) #### Chnage this accordigly 
endDate <- str_sub(ncList[length(ncList)], start = 1, end = 8) #### Chnage this accordigly 

## apply the function
system.time(llply(ncList, read_nc, region = "BC", csvDir = csvDir, .parallel = TRUE))
system.time(llply(ncList, read_nc, region = "CC", csvDir = csvDir, .parallel = TRUE))
system.time(llply(ncList, read_nc, region = "CalC", csvDir = csvDir, .parallel = TRUE))
system.time(llply(ncList, read_nc, region = "HC", csvDir = csvDir, .parallel = TRUE))
```

