---
title: "Bathymetry"
author: "Amieroh Abrahams"
date: "04 June 2019"
output: html_document
---

```{r}
library(ncdf4)
library(data.table)
library(tidyverse)
library(reshape2)


bbox <- data.frame(BC = c(-35, -25, 15, 20), # Benguela Current
                   CC = c(25, 35, -20, -5), # Canary Current
                   CalC = c(30, 50, -115, -130), # California Current
                   HC = c(-17.5, -7.5, -85, -70), # Humboldt Current
                   row.names = c("latmin", "latmax", "lonmin", "lonmax"))
                   

ncDir <- "/home/amieroh/Documents/Data/Datasets/GEBCO_2014_Grid"
csvDir <- "/home/amieroh/Documents/Data/Datasets/GEBCO_2014_Grid/csv"
bathy.nc <- paste0(ncDir, "/GEBCO_2014_2D.nc")


# function to extract the dims and data from OISST netCDFs
bathy_nc <- function(ncFile, region = region, csvDir = csvDir, negDeg = FALSE) {
  coords <- bbox[, region]
  reg.adj <- c(0, 0, 360, 360)
  if (negDeg)
    coords <- coords - reg.adj
  nc <- nc_open(ncFile)
  LatIdx <- which(nc$dim$lat$vals > coords[1] & nc$dim$lat$vals < coords[2])
  LonIdx <- which(nc$dim$lon$vals > coords[3] & nc$dim$lon$vals < coords[4])
  z <- ncvar_get(nc,
                 varid = "elevation",
                 start = c(LonIdx[1], LatIdx[1]),
                 count = c(length(LonIdx), length(LatIdx)))
  dimnames(z) <- list(lon = round(nc$dim$lon$vals[LonIdx], 4),
                      lat = round(nc$dim$lat$vals[LatIdx], 4))
  nc_close(nc)
  z <-
    as.tibble(melt(z, value.name = "z"), row.names = NULL) %>%
    na.omit()
  if (negDeg)
    z$lon <- z$lon + 360
  fwrite(z,
         file = paste0(csvDir, "/", region, "_bathy.csv"),
         append = FALSE)
  rm(z)
}

# Read bathy --------------------------------------------------------------

bathy_nc(ncFile = bathy.nc, region = "BC", csvDir = csvDir)
bathy_nc(ncFile = bathy.nc, region = "CC", csvDir = csvDir)
bathy_nc(ncFile = bathy.nc, region = "CalC", csvDir = csvDir, negDeg = TRUE)
bathy_nc(ncFile = bathy.nc, region = "HC", csvDir = csvDir)
```

# Creating the shorelines

```{r}
# Basemap
baseMap <- function(shoreDir, shoreFile) {
  load(paste0(shoreDir, "/", shoreFile))
  region <- sapply(str_extract_all(shoreFile, "\\b[A-Z]+\\b"), paste, collapse = ' ')
  coords <- bbox[, region]
  ggplot(shore, aes(x = lon, y = lat)) +
    geom_polygon(aes(x = long, y = lat, group = group),
                 fill = "#929292", colour = "black", size = 0.1, show.legend = FALSE) +
    xlab("Longitude (°E)") +
    ylab("Latitude (°S)") +
    coord_fixed(ratio = 1,
                xlim = c(coords[3], coords[4]),
                ylim = c(coords[1], coords[2]), expand = FALSE) +
    theme_bw()
  ggsave(paste0(shoreDir, "/", region, "-shore.pdf"), width = 8, height = 8)
}


# 1.3.makeShore.R

library(data.table)
library(ggplot2)

# setup
shoreDir <- "/home/amieroh/Pictures/shores"
gshhsDir <- "/home/amieroh/Documents/Data/Datasets/gshhg-bin-2.3.7"
bbox <- data.frame(BC = c(-35, -25, 15, 20), # Benguela Current
                   CC = c(25, 35, -20, -5), # Canary Current
                   CalC = c(30, 50, -115, -130), # California Current
                   HC = c(-17.5, -7.5, -85, -70), # Humboldt Current
                   row.names = c("latmin", "latmax", "lonmin", "lonmax"))

# fortify function converts an S3 object generated by evalmod to a data frame for ggplot2.

# make the shores
makeShore(shoreDir, gshhsDir, "BC")
makeShore(shoreDir, gshhsDir, "CC")
makeShore(shoreDir, gshhsDir, "CalC")
makeShore(shoreDir, gshhsDir, "HC")
# makeShore(shoreDir, gshhsDir, "GS") # doesn't work due to self-intersection; do differently...
lats <- c(bbox["latmin", "GS"], bbox["latmax", "GS"])
lons <- c(bbox["lonmin", "GS"], bbox["lonmax", "GS"])
shore <- Rgshhs(paste0(gshhsDir, "/gshhs_f.b"), ## run Rgshhs directly; returns list
                xlim = lons, ylim = lats, level = 1, no.clip = FALSE, checkPolygons = TRUE)
shore <- fortify(shore$SP)
save(shore, file = paste0(shoreDir, "/", "GS", "-shore.Rdata"))
remove(shore)
rm(shore)

load(paste0(shoreDir, "/", "BC-shore.Rdata")) # the plotting of the BC requires a different lon specification
coords <- c(-32.5, -22.5, 5, 20)
ggplot(shore, aes(x = lon, y = lat)) +
  geom_polygon(aes(x = long, y = lat, group = group),
               fill = "#929292", colour = "black", size = 0.1, show.legend = FALSE) +
  xlab("Longitude (°E)") +
  ylab("Latitude (°S)") +
  coord_fixed(ratio = 1,
              xlim = c(coords[3], coords[4]),
              ylim = c(coords[1], coords[2]), expand = FALSE) +
  theme_bw()
load("/home/amieroh/Pictures/shores/GS-shore.Rdata")
# plotting
# baseMap(shoreDir, "CalC-shore.Rdata")
# baseMap(shoreDir, "BC-shore.Rdata") # ???
# load(paste0(shoreDir, "/", "CalC-shore.Rdata")) # the plotting of the BC requires a different lon specification
# coords <- c(35, 45, 225, 240)
# ggplot(shore, aes(x = lon, y = lat)) +
#   geom_polygon(aes(x = long, y = lat, group = group),
#                fill = "#929292", colour = "black", size = 0.1, show.legend = FALSE) +
#   xlab("Longitude (°E)") +
#   ylab("Latitude (°S)") +
#   coord_fixed(ratio = 1,
#               xlim = c(coords[3], coords[4]),
#               ylim = c(coords[1], coords[2]), expand = FALSE) +
#   theme_bw()
# ggsave(paste0(shoreDir, "/", "CalC", "-shore.pdf"), width = 8, height = 8)
# baseMap(shoreDir, "EAC-shore.Rdata")
# baseMap(shoreDir, "KC-shore.Rdata")
# baseMap(shoreDir, "GS-shore.Rdata")


BC.layers = list(
  geom_vline(xintercept = seq(10, 45, 5), linetype = "dashed", size = 0.2),
  geom_hline(yintercept = seq(-45, -20, 5), linetype = "dashed", size = 0.2),
  geom_polygon(data = shore, aes(x = X, y = Y),
               colour = "#272822", fill = "#272822", size = 0.2),
  coord_fixed(ratio = 1, xlim = c(-1.875, 53.125), ylim = c(-52.5, -12.5), expand = TRUE),
  scale_x_continuous(expand = c(0, 0), labels = scales::unit_format(unit = "°E", sep = ""), breaks = c(10, 20, 30, 40)),
  scale_y_continuous(expand = c(0, 0), labels = scales::unit_format(unit = "°S", sep = ""), breaks = c(-45, -35, -25)),
  labs(title = NULL, x = NULL, y = NULL)
)

```
























